# -*- coding: utf-8 -*-
"""24-09-02-hello world.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cVqv13WbNp_8RCoP9CV9TlOMO7dP1WB0
"""

print("Hello World")

